### PR TITLE
feat: Migrate to newer CSDK supporting EdgeX v2

### PR DESCRIPTION
**Pull request by iain-anderson**
Signed-off-by: Iain Anderson <iain@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

Service is written for EdgeX v1.x

## What is the new behavior?
Ported to v2.x using latest C SDK

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No
Existing configurations will no longer be valid (as expected for v2)

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

Updated CSDK has dependencies on paho (mqtt) and redis libraries

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by lenny-intel — CHANGES_REQUESTED** [review]

**Review by lenny-intel — APPROVED** [review]
LGTM for config and service name

**Comment by kb2ma** [comment]
@iain-anderson, I apologize but I do not have the time to review.

**Comment by iain-anderson** [comment]
closes #10  (and #7 and #8 )

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
